#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
RES_DIR="$SCRIPT_DIR/../Resources"
SCHEMA_DIR="$RES_DIR/glib-2.0/schemas"

if [ -d "$SCHEMA_DIR" ]; then
  export GSETTINGS_SCHEMA_DIR="$SCHEMA_DIR"
fi

FRAMEWORKS_DIR="$SCRIPT_DIR/../Frameworks"
if [ -d "$FRAMEWORKS_DIR" ]; then
  export DYLD_FALLBACK_LIBRARY_PATH="$FRAMEWORKS_DIR${DYLD_FALLBACK_LIBRARY_PATH:+:$DYLD_FALLBACK_LIBRARY_PATH}"
fi

exec "$SCRIPT_DIR/tsukimi-bin" "$@"
