name: MacOS CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 4 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build-release:
    env:
      RUST_BACKTRACE: full
    strategy:
      matrix:
        include:
          - arch-name: x86_64-macos
            os: macos-13
            target: x86_64-apple-darwin
          - arch-name: arm64-macos
            os: macos-14
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install Dependencies
        run: |
          brew update
          brew install pkg-config gtk4 libadwaita mpv gstreamer libepoxy gettext

      - name: Build
        run: |
          cargo build --release --locked --target ${{ matrix.target }}

      - name: Make MacOS package
        run: |
          mkdir -p Tsukimi.app/Contents/MacOS
          mkdir -p Tsukimi.app/Contents/Resources
          mkdir -p Tsukimi.app/Contents/Resources/glib-2.0/schemas
          cp share/macos/Info.plist Tsukimi.app/Contents/
          cp share/macos/AppIcon.icns Tsukimi.app/Contents/Resources/
          cp share/macos/tsukimi Tsukimi.app/Contents/MacOS/tsukimi
          cp target/${{ matrix.target }}/release/tsukimi Tsukimi.app/Contents/MacOS/tsukimi-bin
          chmod +x Tsukimi.app/Contents/MacOS/tsukimi
          cp resources/moe.tsuna.tsukimi.gschema.xml Tsukimi.app/Contents/Resources/glib-2.0/schemas/
          glib-compile-schemas Tsukimi.app/Contents/Resources/glib-2.0/schemas
          tar -czf tsukimi-${{ matrix.target }}.tar.gz Tsukimi.app/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tsukimi-${{ matrix.target }}
          path: tsukimi-${{matrix.target}}.tar.gz
          compression-level: 0
